### PR TITLE
read_spec_dr7

### PR DESCRIPTION
**Pull request by rezamonadi**
For pixel_mask I used noise_ratio instead of inverse_noise_variance in the original Roman's code (read_spce.m). 
noise_ratio = noise/flux. if noise_ration>2 or pisxel is brightsky, then pixel_mask==1

What do you think?

### CODE REVIEW

**Review by rezamonadi — COMMENTED** [review]
Thanks for this to-do list!
Do you think learning a CIV-free model is better to do first? Actually, I like to train a CIV-free model first and then test them on my data set. I like to train with with half of my CIV-free spectra and then test on the rest of my full sample. What do you think?

**Comment by sbird** [comment]
I think your use of noise_ratio is fine - that code is really just there to exclude the noisiest pixels from training. We often have to adjust the threshold.

**Comment by jibanCat** [comment]
Hi Reza! Do you also have the MATLAB version of the read_spec.m for DR7? So I can test the read_spec on the DR7 .fits file.

And would you mind also PR your CIV repo https://github.com/rezamonadi/gp_C4? Thanks!

**Comment by jibanCat** [comment]
I think we can close this PR now since these changes should belong to gp_c4 repo, not redshift estimation repo.

**Comment by rezamonadi** [comment]
Sure!

**Pull request closed without merging**
